### PR TITLE
Added feature to respect ProgressPreference setting to suppress activity indicator

### PR DESCRIPTION
**Pull request by DailenG**
- Check if PowerShell $ProgressPreference is "SilentlyContinue"
- If true, suppress the activity indicator at Invoke-ChocoCommand

### CODE REVIEW

**Comment by DailenG** [comment]
I've made a GUI app that utilizes ChocoMan and the activity indicator sometimes produces an individual window for each iteration of the progress characters 😂

**Comment by regg00** [comment]
Hey @DailenG 
This PR is broken.
There's a missing `}` in the file you changed and the module is broken.
I get that message when running pretty much every commands:
```powershell
Get-ChocoOutdated

ConvertFrom-Csv: C:\Users\rtlefrancois\OneDrive - Agri-Marché\Documents\GitHub\ChocoMan\Public\Get\Get-ChocoOutdated.ps1:44:42
Line |
  44 |  … ertFrom-Csv (Invoke-ChocoCommand -Arguments $Arguments).RawOutput -De …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'InputObject'. The argument is null. Provide a valid value for the argument, and then try running the command again.
```

**Comment by DailenG** [comment]
Will get this resolved today!

**Comment by regg00** [comment]
Tested and working. Thanks man.

**Pull request merged**
