### PR TITLE
Added PreRelease, Source parameters and fixed a missing parameter declaration

### PR DESCRIPTION
**Pull request by DailenG**
- Most are just adding PreRelease
- Added Source support for some that choco actually supports it
- Fixed missing AskForConfirmation parameter declaration
- Updated function documentations in the script files (not Docs folder)

### CODE REVIEW

**Comment by DailenG** [comment]
I removed one instance where chocolatey was declared as the default source because in some cases, such as several of my clients, the default chocolatey community repo is disabled and local proxy/connector is used instead with a different name

**Comment by DailenG** [comment]
did not do a version bump, fyi

**Comment by regg00** [comment]
Thanks for that. I didn't even thought that the default source could be removed or blocked. 


> I removed one instance where chocolatey was declared as the default source because in some cases, such as several of my clients, the default chocolatey community repo is disabled and local proxy/connector is used instead with a different name

**Review by regg00 — APPROVED** [review]

**Comment by regg00** [comment]
Thanks for the contribution @DailenG

**Pull request merged**
